[package]
name = "serverpulse-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["clock", "serde"] }
encoding_rs = "0.8"
keyring = "3"
serverpulse-core = { path = "../serverpulse-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

